### ISSUE TITLE
Missing example model

### ISSUE THREAD

**Issue by rickhelmus** [KelseyChetnik/MetaCleanData#1]
Hello,

First of all, many thanks for this nice package!

Following [the vignette](https://github.com/KelseyChetnik/MetaClean/blob/master/vignettes/MetaClean_WalkThrough.Rmd), it mentions an example model that can be used. It seems that this was at some point removed from the repository, I was curious if this will be added back at some point?

Thanks,
Rick

**Comment by KelseyChetnik** [comment]
Hi Rick,

Thank you for your interest in our package!

The example model has been included in the latest commit. 

Best,
Kelsey

**Comment by rickhelmus** [comment]
Excellent, many thanks!
